making a trigram language model

In [8]:
words = open('names.txt', 'r').read().splitlines()

In [9]:
words

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn',
 'abigail',
 'emily',
 'elizabeth',
 'mila',
 'ella',
 'avery',
 'sofia',
 'camila',
 'aria',
 'scarlett',
 'victoria',
 'madison',
 'luna',
 'grace',
 'chloe',
 'penelope',
 'layla',
 'riley',
 'zoey',
 'nora',
 'lily',
 'eleanor',
 'hannah',
 'lillian',
 'addison',
 'aubrey',
 'ellie',
 'stella',
 'natalie',
 'zoe',
 'leah',
 'hazel',
 'violet',
 'aurora',
 'savannah',
 'audrey',
 'brooklyn',
 'bella',
 'claire',
 'skylar',
 'lucy',
 'paisley',
 'everly',
 'anna',
 'caroline',
 'nova',
 'genesis',
 'emilia',
 'kennedy',
 'samantha',
 'maya',
 'willow',
 'kinsley',
 'naomi',
 'aaliyah',
 'elena',
 'sarah',
 'ariana',
 'allison',
 'gabriella',
 'alice',
 'madelyn',
 'cora',
 'ruby',
 'eva',
 'serenity',
 'autumn',
 'adeline',
 'hailey',
 'gianna',
 'valentina',
 'isla',
 'eliana',
 'quinn',
 'nevaeh',
 'ivy',
 'sadie',
 'piper',
 'lydia',
 'alexa',
 'josephine',
 'emery',
 'julia'

the count model

In [11]:
trigrams = []
for word in words:
    word = '.' + word + '.'
    for ch1, ch2, ch3 in zip(word, word[1:], word[2:]):
        trigrams.append(ch1 + ch2 + ch3)
        

In [12]:
trigrams

['.em',
 'emm',
 'mma',
 'ma.',
 '.ol',
 'oli',
 'liv',
 'ivi',
 'via',
 'ia.',
 '.av',
 'ava',
 'va.',
 '.is',
 'isa',
 'sab',
 'abe',
 'bel',
 'ell',
 'lla',
 'la.',
 '.so',
 'sop',
 'oph',
 'phi',
 'hia',
 'ia.',
 '.ch',
 'cha',
 'har',
 'arl',
 'rlo',
 'lot',
 'ott',
 'tte',
 'te.',
 '.mi',
 'mia',
 'ia.',
 '.am',
 'ame',
 'mel',
 'eli',
 'lia',
 'ia.',
 '.ha',
 'har',
 'arp',
 'rpe',
 'per',
 'er.',
 '.ev',
 'eve',
 'vel',
 'ely',
 'lyn',
 'yn.',
 '.ab',
 'abi',
 'big',
 'iga',
 'gai',
 'ail',
 'il.',
 '.em',
 'emi',
 'mil',
 'ily',
 'ly.',
 '.el',
 'eli',
 'liz',
 'iza',
 'zab',
 'abe',
 'bet',
 'eth',
 'th.',
 '.mi',
 'mil',
 'ila',
 'la.',
 '.el',
 'ell',
 'lla',
 'la.',
 '.av',
 'ave',
 'ver',
 'ery',
 'ry.',
 '.so',
 'sof',
 'ofi',
 'fia',
 'ia.',
 '.ca',
 'cam',
 'ami',
 'mil',
 'ila',
 'la.',
 '.ar',
 'ari',
 'ria',
 'ia.',
 '.sc',
 'sca',
 'car',
 'arl',
 'rle',
 'let',
 'ett',
 'tt.',
 '.vi',
 'vic',
 'ict',
 'cto',
 'tor',
 'ori',
 'ria',
 'ia.',
 '.ma',
 'mad',
 'adi',


In [13]:
import torch

In [56]:
chars = sorted(list(set(''.join(words))))
atoi = {ch: i+1 for i, ch in enumerate(chars)}
atoi['.'] = 0

In [57]:
atoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [58]:
trigram_array = torch.zeros((27, 27, 27), dtype=torch.int32)

In [134]:
for word in words:
    for ch1, ch2, ch3 in zip(word, word[1:], word[2:]):
        trigram_array[atoi[ch1], atoi[ch2], atoi[ch3]] += 1
trigram_array += 1   #model smoothening by adding 1 to all counts, in case of model smoothening in count models
#the term is known as laplace smoothening

In [60]:
trigram_array

tensor([[[  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1],
         ...,
         [  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1]],

        [[  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   6,  ...,   1,  21,  12],
         [  1,  29,  21,  ...,   1,  13,   1],
         ...,
         [  1,   6,   1,  ...,  18,   7,   4],
         [  1, 390,  14,  ...,   1,  17,  41],
         [  1, 124,   1,  ...,   1,  13,  23]],

        [[  1,   1,   1,  ...,   1,   1,   1],
         [  1,   6,   6,  ...,   5,  32,   5],
         [  1,   9,   1,  ...,   1,  10,   1],
         ...,
         [  1,   1,   1,  ...,   1,   1,   1],
         [  1,   5,   2,  ...,   1,   1,   1],
         [  1,   1,   1,  ...,   1,   1,   1]],

        ...,

        [[  1,   1,   1,  ...,   1,   1,   1],
         [  1,   1,   3,  ...,   1,  11,   1]

In [61]:
print(trigram_array[atoi['a'], atoi['b'], atoi['c']].item())  #an egs of count, in this case
#egs of abc, and we see c follows ab once

2


In [62]:
#since we have our count tensor, we can make predictions, here we use normal random sampling 
#based on prob of chars following each other

In [63]:
#make the probability tensor 
P = trigram_array.float()/trigram_array.sum(2, keepdim=True)

In [64]:
P  #find the prob of each char occuring after its prev two chars

tensor([[[0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         [0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         [0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         ...,
         [0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         [0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         [0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370]],

        [[0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         [0.0018, 0.0018, 0.0110,  ..., 0.0018, 0.0387, 0.0221],
         [0.0019, 0.0545, 0.0395,  ..., 0.0019, 0.0244, 0.0019],
         ...,
         [0.0051, 0.0303, 0.0051,  ..., 0.0909, 0.0354, 0.0202],
         [0.0005, 0.2038, 0.0073,  ..., 0.0005, 0.0089, 0.0214],
         [0.0024, 0.2925, 0.0024,  ..., 0.0024, 0.0307, 0.0542]],

        [[0.0370, 0.0370, 0.0370,  ..., 0.0370, 0.0370, 0.0370],
         [0.0033, 0.0199, 0.0199,  ..., 0.0166, 0.1060, 0.0166],
         [0.0156, 0.1406, 0.0156,  ..., 0.0156, 0.1562, 0.

In [ ]:
#here we see that a lot of the probs are uniform(after the smoothening), since we added 1 to all counts 
#since we use two chars and then look at the next one's prob, lots of pairs get 
#wasted since they are not in the dataset, as we have lots of 
#pairs possible but only some that are actually namelike, so 
#if we start from those pairs, we will get better results and by that
#i mean shorter more namelike results

In [65]:
itoa = {i: ch for ch, i in atoi.items()}

In [66]:
itoa

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [137]:
g = torch.Generator().manual_seed(2147483647)

In [166]:
new_names = []
for _ in range(5):
    char = []
    ix1 = 0
    ix2 = atoi['e'] #generating only those words which start with a
    char.append(itoa[ix2])
    temp = 0
    while True:
        temp = ix2
        ix2 = torch.multinomial((P[ix1, ix2]), num_samples=1, replacement=True, generator=g).item()
        ix1 = temp
        char.append(itoa[ix2])
        if ix2==0:
            break;
    new_names.append(''.join(char))


In [167]:
new_names

['ef.',
 'evanisaleimbellinahmissephosperomilyzleyonelayelileyarmeraylimianasjpmccztkfcgc.',
 'exorseiantolayelaulidinnaviellicianelettelenasj.',
 'evontenisymoriantailynnasmiratersleennichanihaxiuistieanyickeynnakesseethumikamerolarennasaxyoseranienyzionaylynnandriamonzeettefffsvzbnesthawwyceyleovonaurnazikolioriracishdxnceyaniceninoodiyahimsonnirieliauelynnatheigabdumbekaelynzeyanikadqytannaversliustoniersosniximadililianavojulimielanieltuadielinirenlenaryseangtonaliavioiroshahrahirahartnelleetheruvalekksonisuherelynovanava.',
 'exonbledighadenlesleileliaharjprufydiontavaligansharlieashalionslynettinelinasimusturamyriellicarinamakariovinnahkatheemilvelahaianaalissadavenjobilexceeliovaidekamarailleekeindriaherrornidencdkuy.']

In [168]:
#evalutaing the log loss
log_loss = 0
n = 0

for word in words:
    word = '.' + word + '.'
    for ch1, ch2, ch3 in zip(word, word[1:], word[2:]):
        log_loss += torch.log(P[atoi[ch1], atoi[ch2], atoi[ch3]]).item() 
        n += 1
log_loss /= (-n)
print(log_loss)

#a higher log loss as compared to a bigram model for the counting case, as there is more overhead
#in the trigram model as we have only a few sensible pairs(based on the data) but lots of the
#possible pairs are just getting a initial count of 0 and 1 later after smoothening, which was not 
#the case in bigram model where the overhead bw sensible chars and all the chars was very less

#but in theory trigram models shld perfrom better than bigram models as they have more context, and
#this will be seen in the neural network apporoach, which is how it is meant to be done in practice 

3.089372965115049


the NN model

In [177]:
xs1, xs2, ys = [], [], []
for word in words:
    word = '.' + word + '.'
    for ch1, ch2, ch3 in zip(word, word[1:], word[2:]):
        xs1.append(atoi[ch1])
        xs2.append(atoi[ch2])
        ys.append(atoi[ch3])

xs1 = torch.tensor(xs1)
xs2 = torch.tensor(xs2) 
ys = torch.tensor(ys)


In [178]:
import torch.nn.functional as F 

In [179]:
x1enc = F.one_hot(xs1, num_classes=27).float()
x2enc = F.one_hot(xs2, num_classes=27).float()  
yenc = F.one_hot(ys, num_classes=27).float()

In [188]:
#creating a xenc vector for the input which is x1enc appeneded to x2enc inner vector wise, 
#giving us a 54 dim vector for each input, have to use this as opposed to 27 neuron input
#as then it would lose sequential info, as ab and ba say would have the same 27 dim vector repr of
#011000....(27 of them) but they are different, so we need to use a 54 dim vector for each input
xenc = torch.cat((x1enc, x2enc), 1)

In [193]:
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.]])

In [189]:
xenc.shape

torch.Size([196113, 54])

In [218]:
g = torch.Generator().manual_seed(2147483647)

In [223]:
W = torch.randn((54, 27), requires_grad=True, generator=g)

In [224]:
logits = xenc @ W

In [225]:
W.grad = None

In [226]:
#gradient descent
for i in range(500):
    #forward pass to get the loss
    logits = xenc @ W
    count = logits.exp()
    probs = count/count.sum(1, keepdim=True)
    loss = -probs[torch.arange(ys.shape[0]), ys].log().mean() + 0.001*(W**2).mean()
    print(f"epoch: {i} loss: {loss.item()}")

    #backward pass to get the gradients
    W.grad = None
    loss.backward()

    #update the weights
    W.data += -10*W.grad

epoch: 0 loss: 4.2793498039245605
epoch: 1 loss: 4.0857038497924805
epoch: 2 loss: 3.9157466888427734
epoch: 3 loss: 3.768465042114258
epoch: 4 loss: 3.6420226097106934
epoch: 5 loss: 3.5334808826446533
epoch: 6 loss: 3.439603805541992
epoch: 7 loss: 3.357686758041382
epoch: 8 loss: 3.285736560821533
epoch: 9 loss: 3.222252607345581
epoch: 10 loss: 3.165989637374878
epoch: 11 loss: 3.115856170654297
epoch: 12 loss: 3.0708956718444824
epoch: 13 loss: 3.0303025245666504
epoch: 14 loss: 2.993421792984009
epoch: 15 loss: 2.9597320556640625
epoch: 16 loss: 2.928818702697754
epoch: 17 loss: 2.9003472328186035
epoch: 18 loss: 2.874042510986328
epoch: 19 loss: 2.8496744632720947
epoch: 20 loss: 2.827047824859619
epoch: 21 loss: 2.80599308013916
epoch: 22 loss: 2.7863643169403076
epoch: 23 loss: 2.7680325508117676
epoch: 24 loss: 2.750882863998413
epoch: 25 loss: 2.734813928604126
epoch: 26 loss: 2.7197346687316895
epoch: 27 loss: 2.705562114715576
epoch: 28 loss: 2.6922221183776855
epoch: 29 l

In [227]:
W

tensor([[-3.1988,  2.4937,  0.0842,  ..., -0.7910,  0.9349,  0.4622],
        [ 1.2136,  0.7223, -0.0515,  ..., -1.1134,  0.2545, -0.1763],
        [ 0.0175,  1.2562, -0.9390,  ...,  0.4527,  0.5984, -1.0554],
        ...,
        [ 1.0563,  0.5597, -0.9774,  ..., -0.3570,  0.7918, -0.1560],
        [ 1.5444,  1.5410, -1.4410,  ..., -1.0210, -1.9105, -0.7989],
        [ 0.3553,  1.9707,  0.3501,  ..., -1.1561,  1.2000, -0.7681]],
       requires_grad=True)

In [ ]:
#so over the span of 200 epochs, the loss is lower than bigram NN model for the same num of 
#epochs, so trigram models are better than bigram models in theory and in practice(the NN model)

In [228]:
#generating names now
g = torch.Generator().manual_seed(2147483647)

In [229]:
def output_layer(ix1, ix2):
    xenc = torch.cat((F.one_hot(torch.tensor([ix1]), num_classes=27).float(), F.one_hot(torch.tensor([ix2]), num_classes=27).float()), 1)
    logits = xenc @ W
    counts = logits.exp()
    probs = counts/counts.sum(1, keepdim=True)
    return probs

In [260]:
new_names = []
for _ in range(5):
    char = []
    ix1 = 0
    ix2 = 0
    # char.append(itoa[ix2])
    temp = 0
    while True:
        probs = output_layer(ix1, ix2)
        temp = ix2
        ix2 = torch.multinomial((P[ix1, ix2]), num_samples=1, replacement=True, generator=g).item()
        ix1 = temp
        char.append(itoa[ix2])
        if ix2==0:
            break
    print(''.join(char))

errsolaycencelahersamesarymorickionyxknfbjrgartlyjaycehukeirayahanashviressmaphtonanamonyahivestynnyianewenaidesep.
mpbrettaleyssantynczvsuhamukwaylilahccmsidchumbrielenedrinahiessamelygamick.
ydebetqamiryletteencenavorynahrukaidalalaiciandiellamillornaziemmanslannatrougbmzioramiliellishakaizadendriannamalynnevaepqr.
mhiandrelleannaledwbbramirlorianaisdvieliemuhajahiranierosalinavikaylaileytheodaelynnasthibpmkmpurhfzalrkelizie.
csxcxa.
